//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Api.Configurations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Api.Configurations.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already a coach!.
        /// </summary>
        public static string AlreadyACoach {
            get {
                return ResourceManager.GetString("AlreadyACoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already joined to this class!.
        /// </summary>
        public static string AlreadyJoinedClass {
            get {
                return ResourceManager.GetString("AlreadyJoinedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we cannot find related information or the data does not exist!.
        /// </summary>
        public static string CannotFindRelatedInformation {
            get {
                return ResourceManager.GetString("CannotFindRelatedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Schedule should be empty!.
        /// </summary>
        public static string CustomScheduleShouldBeEmpty {
            get {
                return ResourceManager.GetString("CustomScheduleShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully!.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyday Schedule should be empty!.
        /// </summary>
        public static string EverydayScheduleShouldBeEmpty {
            get {
                return ResourceManager.GetString("EverydayScheduleShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been added successfully!.
        /// </summary>
        public static string InsertSuccess {
            get {
                return ResourceManager.GetString("InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Model Object!.
        /// </summary>
        public static string InvalidModelObject {
            get {
                return ResourceManager.GetString("InvalidModelObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Inactive Account..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference number attached!.
        /// </summary>
        public static string NoTelRTranAttached {
            get {
                return ResourceManager.GetString("NoTelRTranAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Configs have been updated successfully!.
        /// </summary>
        public static string NoticationUpdateSuccess {
            get {
                return ResourceManager.GetString("NoticationUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already paid the corresponding amount!.
        /// </summary>
        public static string PaymentAlreadyDone {
            get {
                return ResourceManager.GetString("PaymentAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your card has been expired!.
        /// </summary>
        public static string PaymentMethod_CardExpired {
            get {
                return ResourceManager.GetString("PaymentMethod_CardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any payment..
        /// </summary>
        public static string PaymentNotDone {
            get {
                return ResourceManager.GetString("PaymentNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Recorded!.
        /// </summary>
        public static string RecordedSuccess {
            get {
                return ResourceManager.GetString("RecordedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot send your email as of the moment, please try again later!.
        /// </summary>
        public static string SendEmailFailed {
            get {
                return ResourceManager.GetString("SendEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent successfully!.
        /// </summary>
        public static string SendEmailSuccess {
            get {
                return ResourceManager.GetString("SendEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Process of Payment has been successful!.
        /// </summary>
        public static string SuccessInitPayment {
            get {
                return ResourceManager.GetString("SuccessInitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized!.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully!.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile Update failed! Invalid UserId..
        /// </summary>
        public static string UserProfileUpdateFailed {
            get {
                return ResourceManager.GetString("UserProfileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile Update Success!.
        /// </summary>
        public static string UserProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("UserProfileUpdateSuccess", resourceCulture);
            }
        }
    }
}
